### PR TITLE
Set INSERT_LINE_BREAK_AFTER_LAST_ATTRIBUTE=false; Also set XML_ALIGN_…

### PR DESCRIPTION
**Pull request by worker8**
In this PR, I changed `XML_ALIGN_ATTRIBUTES` to `false`. I think this will make it easier to visualize the depth of a child item. Take below as an example:

This is before the change: 
- Note that the attributes of `CircularProgressBar` is not aligned with the attributes of `TextView` due to this setting, so it is hard to visualize that these two items are located at the same depth.
  

So after the change, it will look like this:
- Note that it is easier to see that `CircularProgressBar` and `TextView` are nested at the same depth under the `LinearLayout`.
  

After that, I also changed `INSERT_LINE_BREAK_AFTER_LAST_ATTRIBUTE` to `false`. This is about adding a new line after the last attribute. I am thinking that this will help to save one line per item in the xml, so the xml will generally become a little shorter, so it is easier to read since we can now fit more things into one screen.

This is how it looks like finally:

Let me know what do you think. Thanks!

### CODE REVIEW

**Comment by gfx** [comment]
Can you apply the changes to example code and add new example related to this?

**Comment by worker8** [comment]
Made some changes to the example to make it more complicated, so that we can see the code style in action for the xml. Screen looks like this now:

**Comment by gfx** [comment]
Looks good. Thanks.

@nein37 @komatatsu What do you think of it?

**Comment by koyama-kani-daisuki** [comment]
LGTM 👍

**Pull request merged**
